spring:
  profiles:
    active: dev
---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.my.springcloud.api.bean    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml      # mapper映射文件

spring:
  profiles: dev
  application:
    name: ms-product  # 指定应用名称，这在以后的服务与服务之间相互调用都是根据这个name进行调用
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3307/springcloud_db01?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true # 服务注册，false表示不注册（服务本身无需注册）
    fetch-registry: true       # 服务发现，false表示不发现（服务本身无需发现微服务）
    # 微服务注册中心的服务地址
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka

---
server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  type-aliases-package: com.my.springcloud.api.bean    # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/*.xml      # mapper映射文件

spring:
  profiles: prod
  application:
    name: ms-product  # 指定应用名称，这在以后的服务与服务之间相互调用都是根据这个name进行调用
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3307/springcloud_db02?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true # 服务注册，false表示不注册（服务本身无需注册）
    fetch-registry: true       # 服务发现，false表示不发现（服务本身无需发现微服务）
    # 微服务注册中心的服务地址
    service-url:
      defaultZone: http://eureka6001.com:6001/eureka
