spring:
  profiles:
    active: dev
---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: ms-config-eureka

eureka:
  instance:
    hostname: eureka6001.com # eureka服务端的实例名称
  client:
    register-with-eureka: false # 服务注册，false表示不注册（服务本身无需注册）
    fetch-registry: false       # 服务发现，false表示不发现（服务本身无需发现微服务）
    # 暴露给微服务客户端的服务地址
    service-url:
      # 单机版配置
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      # 集群版配置,配置其他集群机器的暴露地址(多台集群使用逗号隔开)
      # defaultZone: http://eureka6002.com:6002/eureka,http://eureka6003.com:6003/eureka
      defaultZone: http://eureka6001.com:6001/eureka

  server:
    # 关闭Eureka的自我保护机制（默认开启true）
    enable-self-preservation: false
---
server:
  port: 6001
spring:
  profiles: prod
  application:
    name: ms-config-eureka

eureka:
  instance:
    hostname: eureka6001.com # eureka服务端的实例名称
  client:
    register-with-eureka: false # 服务注册，false表示不注册（服务本身无需注册）
    fetch-registry: false       # 服务发现，false表示不发现（服务本身无需发现微服务）
    # 暴露给微服务客户端的服务地址
    service-url:
      # 单机版配置
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      # 集群版配置,配置其他集群机器的暴露地址(多台集群使用逗号隔开)
      # defaultZone: http://eureka6002.com:6002/eureka,http://eureka6003.com:6003/eureka
      defaultZone: http://eureka6001.com:6001/eureka

  server:
    # 关闭Eureka的自我保护机制（默认开启true）
    enable-self-preservation: true